# Site settings
title: Mr. Wojahn
email: aaron.wojahn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mr. Wojahn's Calculus and Advanced Algebra courses.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://woaa0201.github.io" # the base hostname & protocol for your site
twitter_username: aaronwoj
github_username:  woaa0201

# Build settings
markdown: kramdown
